### ISSUE TITLE
Some Improvement Suggestions

### ISSUE THREAD

**Issue by edwintcloud** [ByeonghoonJeon/practice-file#2]
@ByeonghoonJeon  could you imagine some ways to improve your password_generate program? I can.

You can have a look at this resource for ideas: [Python3 Common String Operations](https://docs.python.org/3/library/string.html) and also here's a free one: a function defined `def generate_password(num_of_letters, num_of_digits):` that handles the logic of generating a password.

**Comment by edwintcloud** [comment]
maybe this is more helpful: try this out in a python program 
```python
import string
letters = list(string.ascii_letters)
numbers = list(string.digits)
symbols = list(string.punctuation)
print(letters, numbers, symbols)
```

**Comment by ByeonghoonJeon** [comment]
Thank you for your kind comment.
I revised codes with your suggestion.
Have a nice day.
